config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :posts do
    resources :comments
  end

  root 'posts#index' 
  get '/posts/hashtag/:name', to: 'posts#hashtags'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags
  validates :title, presence: true
  validates :body, presence: true

  after_create do
    post = Post.find_by(id: self.id)
    hashtags = self.body.scan(/#\w+/)
    hashtags.uniq.each do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      post.tags << tag
    end
  end


  before_update do
    post = Post.find_by(id: self.id)
    post.tags.clear # remove all tags from post when updating it, add it again
    hashtags = self.body.scan(/#\w+/)
    hashtags.uniq.each do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      post.tags << tag
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  validates :name, presence: true, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def edit
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment created!' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to @post, alert: 'Comment body can not be empty!' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @comment = Comment.find(params[:id])
    @post = @comment.post

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @post, notice: "Comment updated!" }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to @post
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user!, only: [:index, :show, :hashtags]

  def index
    @posts = Post.all.order(created_at: :desc)
    @post = Post.new
  end

  def show
  end

  def hashtags
    tag = Tag.find_by(name: params[:name])
    @posts = tag.posts
  end

  def new
    @post = current_user.posts.build
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post created!" }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post updated!" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post deleted!" }
      format.json { head :no_content }
    end
  end


  private

  def set_post
    @post = Post.find(params[:id])
  end
  
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_with_hashtags(body)
    body.gsub(/#\w+/) { |word| link_to word, "/posts/hashtag/#{word.delete('#')}" }.html_safe
  end

  def trending_hashtags
    tags = Post.all.sample(200).collect { |post| post.tags }.flatten
    trending_tags = Hash.new(0)
    tags.each {|tag| trending_tags[tag] += 1 }

    trending_tags.sort_by { |tag, count| -count }.take(6).collect {|arr| arr.first.name}
  end
end

app/views/comments/_comment.html.erb
<div class="comment">
    <p style="white-space: pre-line; font-size: 1.1rem" class=""> <%= comment.body %> </p>
    
    <div class="level is-mobile mt-0 mb-1" >
        <div class="level-left" >
            <div class="level-item has-text-centered ">
            
                <div class="level-item">
                    <small>
                        <strong>
                            <% if user_signed_in? %>
                                <%= comment.user.name %>
                            <% else %>
                                Anonymous
                            <% end %>
                        </strong>
                        <%= time_ago_in_words(comment.created_at) %>
                        ago
                    </small>
                </div>
            </div>

            <% if comment.created_at != comment.updated_at%>
                <div class="level-item">
                    <small>
                        edited
                        <%= time_ago_in_words(comment.updated_at) %>
                        ago
                    </small>
                </div>
            <% end %>

            <% if comment.user == current_user %>
                <%= link_to edit_post_comment_path(@post, comment), class: "level-item mr-0" do %>
                    <span class="icon"><i class="fas fa-edit is-size-5"></i></span>
                <% end %>

                <%= link_to [@post, comment], method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' }, class:"level-item" do %>
                    <span class="icon"> <i class="fas fa-trash-alt is-size-5"></i></span>
                <% end %>

                
            <% end %>
        </div>
    </div>
</div>

app/views/comments/_form.html.erb
<% if controller.action_name == 'edit' %>
    <%= simple_form_for [@post, @comment] do |f| %>
        <%= f.error_notification %>
        <div class="field">
            <div class="control">
                <%= f.input :body, input_html: { class: "textarea" }, wrapper: false, label: false %>
            </div>
        </div>

        <div class="field">
            <div class="control">
                <%= f.button :submit, 'Comment', class: "button is-info " %>
            </div>
        </div>
        <%= link_to 'Go back', @post, class: "button"%>
    <% end %>  
<% else %> 
    <%= simple_form_for [@post, @post.comments.build] do |f| %>
        <%= f.error_notification %>
        <div class="field">
            <div class="control">
                <%= f.input :body, input_html: { class: "textarea" }, wrapper: false, label: false %>
            </div>
        </div>

        <div class="field">
            <div class="control">
                <%= f.button :submit, 'Comment', class: "button is-info " %>
            </div>
        </div>
    <% end %>
<% end %>

app/views/comments/edit.html.erb
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-4">
                <h2 class="title"> Edit Comment </h2>
                <%= render 'comments/form' %>
            </div>
        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clubhouse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"> <%= notice %> </p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"> <%= alert %> </p>
      </div>
    <% end %>

    <nav class="navbar is-white">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-size-4"> <span class="icon mr-1"><i class="fas fa-ship"></i></span> Clubhouse </h1>
        <% end %>

        <%# mobile menu %>



      </div>

    <div id="main-nav" class="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped">
          
            <% if user_signed_in? %>
              
              <%= link_to current_user.name, edit_user_registration_path, class: "button is-link is-light control" %>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete,  class: "button is-info control is-inverted" %>

            <% else %>

              <%= link_to "Sign Up", new_user_registration_path, class: "button is-info control" %>
              <%= link_to "Sign In", new_user_session_path, class: "button is-info is-light control" %>

            <% end %>
          
          </div>
        
        </div>
      </div>
    </div>

    </nav>

    <%= yield %>
  </body>
</html>

app/views/posts/_aside-menu.html.erb
<div class="column is-3">
    <%= link_to "Create Post", new_post_path, class:"button is-info is-rounded mb-5 is-medium" %>
    <div class="panel">
        <p class="panel-heading"> Trending </p>

        <% trending_hashtags.each do |tag_name| %>
            <%= link_to "/posts/hashtag/#{tag_name}", class: "panel-block" do %>
                <span class="tag is-link is-light is-medium"> <%= tag_name %> </span>
            <% end %>
        <% end %>
    
    </div>
    
</div>

app/views/posts/_feed.html.erb
<div class="column is-9">

    <% if controller.action_name == 'hashtags' %>
        <h1 class="title is-4 has-text-link"> #<%= params[:name] %> </h1>
    <% end %>
    <div class="box post-container">

        <% posts.each do |post| %>
        
            <div class="content p-2 post" >
                <h1 class="title is-5">
                    <%= link_to post.title, post %>
                </h1>
                <div class="level is-mobile  mb-1">
                    <div class="level-left">

                        <div class="level-item">
                            <small>
                                submitted by
                                <strong>
                                    <% if user_signed_in? %>
                                        <%= post.user.name %>
                                    <% else %>
                                        Anonymous
                                    <% end %>
                                </strong>
                                <%= time_ago_in_words(post.created_at) %>
                                ago
                            </small>
                        </div>


                    </div>
                    <div class="level-right">
                        <span class="level-item icon mr-1">
                            <i class="far fa-comments has-text-grey "></i>
                        </span>
                        <p class="has-text-grey"> <%= post.comments.length %></p>
                    </div>
                </div>

                
                <% if post.created_at != post.updated_at%>
                    <small >
                        edited
                        <%= time_ago_in_words(post.updated_at) %>
                        ago <br>
                    </small>
                    
                <% end %>
                
                <% if post.user == current_user %>
                    <br>
                    <%= link_to edit_post_path(post), class: " mr-0" do %>
                        <span class="icon"><i class="fas fa-edit is-size-5"></i></span>
                    <% end %>

                    <%= link_to post, method: :delete, data: { confirm: "Are you sure you want to delete this post?" }, class:"" do %>
                        <span class="icon"> <i class="fas fa-trash-alt is-size-5"></i></span>
                    <% end %>
                <% end %>

            
            </div>

        <% end %>
    
    </div>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
    <%= f.error_notification %>

    <div class="field">
        <div class="control">
            <%= f.input :title, wrapper: false, required: true, input_html: { autocomplete: true, class: "input" }, 
            label_html: { class: "label" }%>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= f.input :body, wrapper: false, required: true, input_html: {class: "textarea" }, 
            label_html: { class: "label" }%>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= f.button :submit, "Submit", class: "button is-info" %>
        </div>
    </div>

    <% if controller.action_name == 'edit' %>
        <%= link_to 'Go Back', @post, class: "button" %>
    <% else %>
        <%= link_to 'Go Back', root_path, class: "button" %>
    <% end %>
<% end %>

app/views/posts/edit.html.erb
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-4">
                <h1 class="title"> Edit Post </h1>
                <%= render 'form', post: @post %>   
            </div>
        </div>
    </div>
</section>

app/views/posts/hashtags.html.erb
<div class="section">
    <div class="container">
        <div class="columns">
            <%= render 'aside-menu' %>
            <%= render 'feed', posts: @posts %>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
<div class="section">
    <div class="container">
        <div class="columns">
            <%= render 'aside-menu' %>
            <%= render 'feed', posts: @posts %>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-4">
                <h1 class="title"> New Post </h1>
                <%= render 'form', post: @post %>   
            </div>
        </div>
    </div>
</section>

app/views/posts/show.html.erb
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-9">

                <h1 class="title is-3 "> <%= link_to @post.title, @post %> </h1>

                <div class="level is-mobile" >
                    <div class="level-left" >
                        <div class="level-item has-text-centered ">
                            <small>
                                submitted by
                                <strong>
                                    <% if user_signed_in? %>
                                        <%= @post.user.name %>
                                    <% else %>
                                        Anonymous
                                    <% end %>
                                </strong>
                                <%= time_ago_in_words(@post.created_at) %>
                                ago
                            </small>
                        </div>

                        <% if @post.created_at != @post.updated_at%>
                            <div class="level-item">
                                <small>
                                    edited
                                    <%= time_ago_in_words(@post.updated_at) %>
                                    ago
                                </small>
                            </div>
                        <% end %>

                        <% if @post.user == current_user %>
                            <%= link_to edit_post_path(@post), class: "level-item mr-0" do %>
                                <span class="icon"><i class="fas fa-edit is-size-5"></i></span>
                            <% end %>

                            <%= link_to @post, method: :delete, data: { confirm: "Are you sure you want to delete this post?" }, class:"level-item" do %>
                                <span class="icon"> <i class="fas fa-trash-alt is-size-5"></i></span>
                            <% end %>
                        <% end %>

                    </div>
                </div>
                <div class="box">
                    <p style="white-space: pre-line;" > <%= render_with_hashtags(@post.body) %> </p>
                </div> 

                
                <div class="box" style="max-width: 700px;">

                    <div class="content comments-container">
                        <h2 class="title"> Comments </h2>
                        <%= render @post.comments %>
                    </div>
                    
                    <h3 class="title is-5"> New Comment </h3>
                    <%= render 'comments/form' %>
                    
                </div>
            </div>

            
        </div>
    </div>
</section>